version: "3"
services:
  db:
    image: mysql:8.0.26
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "${TYPEORM_PORT_HOST}:${TYPEORM_PORT_CONTAINER}"
    environment:
      MYSQL_TCP_PORT: ${TYPEORM_PORT_CONTAINER}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${TYPEORM_DATABASE}
      MYSQL_USER: ${TYPEORM_USERNAME}
      MYSQL_PASSWORD: ${TYPEORM_PASSWORD}
      networks: host

  adminer:
    image: adminer:4.8.0
    restart: always
    ports:
      - 8081:8080
